'use client';
import {useEffect,useRef,useState} from 'react';
import {FeatureShowcase} from './showcase';
import {MotionPortal as Portal} from './motion-portal';
const B='/portfolio/';
const nav=[['northstar','NorthStar','AI CONTENT COPILOT'],['plateforge','PlateForge','AI FOOD COMPANION'],['architecture','空间与叙事','ARCHITECTURE / 4 WORKS'],['about','关于宛珈','ABOUT & EXPERIENCE'],['nivea','NIVEA','BRAND & GROWTH']];
const works=[
 {title:'聚场',en:'A stage for stories.',sub:'当代戏剧博物馆',meta:'独立设计 · 2020 秋',text:'让参观成为一场行走中的戏剧。通过空间的聚合、交错与展开，探索公共建筑中的叙事与意义表达。',pages:[5,7,8,9]},
 {title:'拼贴之家',en:'A home for a singular soul.',sub:'为戏剧家汉诺赫·列文而作',meta:'独立设计 · 2021 春',text:'以戏剧家的独特灵魂为线索，将生活、写作与剧场编织进一个家。片段之间的碰撞，成为空间本身的语言。',pages:[14,12,13,10]},
 {title:'胡同里的手艺人',en:'Mending the urban fabric.',sub:'基于胡同肌理的织补与重构',meta:'合作设计 · 2021 春',text:'在已有的城市记忆中寻找新生活的入口。以商业综合体为载体，连接街巷尺度、公共活动与日常手艺。',pages:[19,16,17,18]},
 {title:'生长的街区',en:'A neighborhood that evolves.',sub:'进化逻辑下生成的实验性街区',meta:'合作设计 · CAAD · 2020 夏',text:'以 Wallacei 进化算法探索单元组织，让规则、选择与组合共同塑造建筑。设计不仅是结果，也是不断生成的过程。',pages:[23,21,22,20]}
];
const arch=(n:number)=>B+'arch-'+String(n).padStart(2,'0')+'.jpg';
const nivea=(n:number)=>B+'nivea-'+String(n).padStart(3,'0')+'.jpg';
function Motion({id,kind,children}:{id:string,kind:string,children:React.ReactNode}){const ref=useRef<HTMLElement>(null);useEffect(()=>{let frame=0;const update=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const el=ref.current;if(!el)return;const r=el.getBoundingClientRect();el.style.setProperty('--p',String(Math.max(0,Math.min(1,-r.top/Math.max(1,r.height-innerHeight)))));});};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);return()=>{removeEventListener('scroll',update);removeEventListener('resize',update);cancelAnimationFrame(frame);};},[]);return <><section id={id} className={kind} ref={ref}>{children}</section>{(id==='northstar'||id==='plateforge')&&<FeatureShowcase product={id}/>}</>}
export default function Home(){
const [active,setActive]=useState('home'),[open,setOpen]=useState<{src:string,title:string}|null>(null),[ns,setNs]=useState(0),[pf,setPf]=useState(0);const dialog=useRef<HTMLDialogElement>(null);
useEffect(()=>{const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:'-20% 0px -60% 0px'});document.querySelectorAll('main>section[id]').forEach(el=>obs.observe(el));return()=>obs.disconnect();},[]);
useEffect(()=>{if(open){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[open]);
const zoom=(src:string,title:string)=>setOpen({src,title});
return <main>
<Portal/>
<header><a className="brand" href="#home"><span>✳</span> WANJIA WU <small>邬宛珈</small></a><span className="header-note">IDEAS, GROWN INTO EXPERIENCES.</span><a href="mailto:wu-wj24@mails.tsinghua.edu.cn">Let’s talk ↗</a></header>
<nav className={'rail '+(active==='home'?'hidden':'')} aria-label="章节导航">{nav.map(([id,label],i)=><a key={id} href={'#'+id} className={active===id?'active':''}><span>0{i+1}</span><b>{label}</b></a>)}</nav>
<Motion id="home" kind="hero-scroll"><div className="hero-sticky"><div className="hero-bg"/><span className="hero-kicker">A PERSONAL COLLECTION / 2026</span><div className="hero-title"><span>Welcome to</span><h1>my creative<br/><em>garden.</em></h1><p>我是邬宛珈。<br/>在 AI 产品、空间设计与商业之间，<br/>把想法种成可以被体验的作品。</p></div><img className="hero-island" src={B+'office-island.png'} alt="花草与电脑组成的漂浮办公岛"/><img className="hero-food" src={B+'food-sculpture.png'} alt="绿色食材与餐具的漂浮装置"/><div className="index"><span className="eyebrow">THE INDEX / 目录</span>{nav.map(([id,label,sub],i)=><a key={id} href={'#'+id}><i>0{i+1}</i><div><b>{label}</b><small>{sub}</small></div><span>↗</span></a>)}</div><div className="hero-bottom"><span>PRODUCT · SPACE · STRATEGY</span><a href="#northstar">Scroll to explore ↓</a><span>BEIJING / BARCELONA</span></div></div></Motion>
<Motion id="northstar" kind="product-scroll north"><div className="product-sticky"><span className="section-no">01 / AI PRODUCT</span><div className="product-title"><span className="eyebrow">A CLEARER DIRECTION FOR CREATORS</span><h2>NorthStar<small>北极星</small></h2><p>从“看见数据”，到<br/><em>知道下一步怎么做。</em></p></div><div className="collage north-collage"><img className="office" src={B+'office-island.png'} alt="漂浮绿色办公装置"/><button className="desktop" onClick={()=>zoom(B+'northstar-ui.png','NorthStar · 真实经营看板界面')}><div className="window-bar">● ● ● <span>northstar / workspace</span> ↗</div><img src={B+'northstar-ui.png'} alt="NorthStar 经营看板和 Cue 助手真实产品界面"/></button><span className="floating-label">✦ Your next move, made clear.</span></div><div className="product-copy"><span className="pill">内容经营 AI 助手</span><p>面向内容创作者，将经营看板、知识库、选题脚本与直播复盘放进同一个工作空间。Cue 把账号表现与内容知识连接起来，帮助创作者找到下一步。</p><div className="tabs">{['经营洞察','内容创作','知识沉淀'].map((s,i)=><button className={ns===i?'selected':''} key={s} onClick={()=>setNs(i)}>{s}</button>)}</div><div className="tab-copy" key={ns}><b>{['把数据变成行动','让想法走向发布','让积累被再次调用'][ns]}</b><p>{['聚合播放、粉丝与内容表现，连接“下周做什么、下条怎么拍、下场怎么改”的决策。','短视频脚本、直播脚本与排期相互连接，减少工具之间反复切换。','围绕知识库、对标账号与素材库，建立持续积累的创作上下文。'][ns]}</p></div><a className="project-link" href="http://northstar-copilot.com/" target="_blank" rel="noreferrer">打开真实产品 ↗</a><small className="note">产品界面实拍 · 界面内为示例账号数据</small></div></div></Motion>
<Motion id="plateforge" kind="product-scroll plate"><div className="product-sticky"><span className="section-no">02 / AI PRODUCT</span><div className="product-title"><span className="eyebrow">GOOD FOOD. LESS FRICTION.</span><h2>PlateForge<small>每日饮食伙伴</small></h2><p>把“今天吃什么”，<br/><em>变成触手可及的一餐。</em></p></div><div className="collage plate-collage"><img className="food" src={B+'food-sculpture.png'} alt="绿色食材、餐盘与咖啡组成的创意装置"/><button className="phone" onClick={()=>zoom(B+'plateforge-ui.png','PlateForge · 真实计划配置界面')}><div className="phone-top">PlateForge <span>✦</span></div><img src={B+'plateforge-ui.png'} alt="PlateForge 热量目标、饮食偏好与烹饪时间配置界面"/></button><span className="floating-label">Fresh ideas, every day.</span></div><div className="product-copy"><span className="pill">AI Meal Planning</span><p>从热量目标、口味偏好到可用时间，让饮食计划适应真实生活。连接食谱、食材库存与个人目标，缩短从选择到动手的距离。</p><div className="tabs">{['个性化计划','食谱与烹饪','食材管理'].map((s,i)=><button className={pf===i?'selected':''} key={s} onClick={()=>setPf(i)}>{s}</button>)}</div><div className="tab-copy" key={pf}><b>{['先理解今天的你','从一道菜，到一次动手','从已有食材出发'][pf]}</b><p>{['设置每日热量预算、高蛋白等偏好、菜系与烹饪时间，建立属于自己的饮食计划。','浏览食谱、收藏喜欢的菜肴，用分步烹饪视图降低执行门槛。','在 Pantry 中管理食材，让采购、库存与每日选择更连贯。'][pf]}</p></div><a className="project-link" href="http://106.53.42.148:3000/" target="_blank" rel="noreferrer">打开真实产品 ↗</a><small className="note">产品界面实拍 · AI 饮食规划原型</small></div></div></Motion>
<section id="architecture" className="architecture"><div className="gallery-heading"><div><span className="eyebrow">03 / SELECTED ARCHITECTURE</span><h2>空间，是另一种<em>叙事。</em></h2></div><p>四组作品，一条设计线索。<br/>从人的体验出发，探索空间、路径与关系。</p><i>01 — 04</i></div>{works.map((w,i)=><Motion key={w.title} id={'work-'+i} kind={'work-scroll work-'+i}><div className="work-sticky"><div className="work-copy"><span className="eyebrow">EXHIBITION / 0{i+1}</span><h3>{w.title}</h3><em>{w.en}</em><h4>{w.sub}</h4><p>{w.text}</p><span className="work-meta">{w.meta}</span><small>点击图纸 / 模型，可放大查看 ↗</small></div><div className="board">{w.pages.map((n,j)=><button key={n} onClick={()=>zoom(arch(n),w.title+' · 原始图版 '+n)}><img loading="lazy" src={arch(n)} alt={w.title+' · '+['空间印象','设计研究','模型与空间','图纸细节'][j]}/><span>{['空间印象','设计研究','模型与空间','图纸细节'][j]} <b>↗</b></span></button>)}</div><span className="work-count">0{i+1}<small>/ 04</small></span></div></Motion>)}</section>
<section id="about" className="about"><div className="about-picture"><img src={B+'green-gallery.jpg'} alt="阳光照进长满绿草的建筑空间"/><span>BETWEEN<br/>STRUCTURE<br/>& POSSIBILITY.</span></div><div className="about-copy"><span className="eyebrow">04 / ABOUT ME</span><h2>邬宛珈<em>Maggie / Wanjia Wu</em></h2><p className="intro">建筑训练给我空间与叙事的视角，<br/>商业分析让我理解增长与选择，<br/><em>AI 产品让我把想法变成真实体验。</em></p><div className="numbers"><div><b>25w+</b><span>自媒体关注者</span></div><div><b>100+</b><span>场直播实践</span></div><div><b>30w+</b><span>10 个月创业营收 / 元</span></div></div><h3 className="resume-label">EDUCATION / 教育</h3>{[['2024—2027','清华大学 · 经济管理学院','管理硕士'],['2026','ESADE Business School','CEMS 交换 · 巴塞罗那'],['2018—2024','清华大学 · 建筑学院','建筑学工学学士 · GPA 3.78/4.0 · 关肇邺设计奖学金']].map(([date,title,desc])=><div className="resume-row" key={title}><span>{date}</span><div><b>{title}</b><p>{desc}</p></div></div>)}<h3 className="resume-label">EXPERIENCE / 经历</h3>{[['2026.06—至今','腾讯 IEG · AI 产品经理','Data & AI Group / Agent、知识库与数据产品'],['2025.11—2026.01','快手 · 战略投资','聚焦可灵 AI / 用户分析、行业研究与商业模型'],['2025.04—09','字节跳动 · 商业分析','生活服务战略与经营 / 产品机会与营销策略']].map(([date,title,desc])=><div className="resume-row" key={title}><span>{date}</span><div><b>{title}</b><p>{desc}</p></div></div>)}<p className="skills">Vibe coding · SQL · Python · R · Tableau · Adobe</p><p className="personal">工作之外：戏剧导演与表演、美声、游泳、现代舞。<br/>喜欢有结构的思考，也喜欢让想象力自由生长。</p><a className="project-link" href="mailto:wu-wj24@mails.tsinghua.edu.cn">联系我 ↗</a></div></section>
<section id="nivea" className="nivea"><div className="case-page"><div className="case-heading"><span className="eyebrow">05 / STRATEGY & BRAND GROWTH</span><div><h2>NIVEA<em>Accelerate TikTok Shop growth.</em></h2><span className="nivea-logo">NIVEA</span></div><p>CEMS 校企合作 · 巴塞罗那 · 2026 / 团队项目</p></div><div className="case-grid"><div><span className="eyebrow">01 / THE DIAGNOSIS</span><h3>不是更多信息，<br/>而是更好的<em>创作入口。</em></h3><p>结合经营数据、20 人消费者调研、创作者访谈与品牌 benchmark，将增长问题落到可执行的达人内容策略。</p><p>Briefing 的核心转变：从品牌的产品说明书，走向创作者真正用得上的内容 playbook。</p><div className="diagnosis">{['笼统视觉要求 → 具体画面与拍摄参考','只讲产品卖点 → 连接场景与用户痛点','直接催促购买 → 互动与转化双层 CTA'].map((s,i)=><div key={s}><i>0{i+1}</i><span>{s}</span></div>)}</div></div><div className="mosaic">{[31,35,41,46].map(n=><button key={n} onClick={()=>zoom(nivea(n),'NIVEA · Briefing benchmark')}><img loading="lazy" src={nivea(n)} alt={'NIVEA briefing 对标原始图版 '+n}/></button>)}<small>项目原始图版 · 点击放大</small></div></div></div><div className="case-page solution"><span className="eyebrow">02 / THE CREATOR PLAYBOOK</span><div className="solution-heading"><h3>给创作自由，<br/><em>也给清晰的支持。</em></h3><p>以 NIVEA UV Stick 为例，把诊断转化为分层 brief：<br/>核心产品卡 + 场景参考 + 差异化创作者指引。</p></div><div className="solution-images">{[51,48,49].map(n=><button key={n} onClick={()=>zoom(nivea(n),'NIVEA · 创作者 Brief 提案')}><img loading="lazy" src={nivea(n)} alt={'NIVEA 创作者 Playbook 原始图版 '+n}/></button>)}</div><div className="case-bottom">{[['Storyteller','精简核心信息，保留个人叙事与表达自由。'],['Pure Seller','提供更清晰的场景、结构与转化指引。'],['Business connection','将内容、affiliate 策略与三情景收入模型连接。']].map(([s,d])=><div key={s}><em>{s}</em><p>{d}</p></div>)}</div><small className="note">展示为校企合作团队方案；策略建议与预测不代表已实现的经营结果。产品功效表述以品牌正式审核为准。</small></div></section>
<footer><span className="eyebrow">LET’S GROW SOMETHING GOOD.</span><h2>下一个想法，<br/><em>一起发生。</em></h2><a href="mailto:wu-wj24@mails.tsinghua.edu.cn">wu-wj24@mails.tsinghua.edu.cn ↗</a><div><span>© 2026 Wanjia Wu · Selected works</span><span>AI 产品 / 建筑 / 商业策略</span><a href="#home">Back to the garden ↑</a></div></footer>
<dialog ref={dialog} className="lightbox" onCancel={()=>setOpen(null)} onClick={e=>{if(e.target===e.currentTarget)setOpen(null);}}><div><span>{open?.title}</span><button onClick={()=>setOpen(null)} aria-label="关闭大图">关闭 ×</button></div>{open&&<img src={open.src} alt={open.title}/>}</dialog>
</main>}
