'use client';
import {useEffect,useRef,useState} from 'react';
const B='/portfolio/';
export function Portal(){
 const canvas=useRef<HTMLCanvasElement>(null),reveal=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=canvas.current,layer=reveal.current;if(!el||!layer)return;const ctx=el.getContext('2d');if(!ctx)return;let raf=0,w=0,h=0;const seeds=Array.from({length:620},(_,i)=>({a:i/620*Math.PI*2,r:Math.random(),speed:.5+Math.random(),size:.5+Math.random()*2}));const targets=[['northstar','forest-office.jpg'],['plateforge','food-background.jpg'],['architecture','building-background.jpg'],['about','green-gallery.jpg'],['nivea','portal-background.jpg']];const resize=()=>{w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio,1.5);el.width=w*d;el.height=h*d;ctx.setTransform(d,0,0,d,0,0);};resize();addEventListener('resize',resize);
 const render=(time:number)=>{ctx.clearRect(0,0,w,h);let p=-1;let bg='';for(const [id,img] of targets){const top=document.getElementById(id)?.getBoundingClientRect().top;if(top!==undefined&&top<h*.82&&top>h*-.12){p=1-(top+h*.12)/(h*.94);bg=img;break;}}
 if(p>=0){const envelope=Math.sin(Math.PI*p);const radius=Math.min(w,h)*(.11+p*p*1.15),cx=w*.5,cy=h*.51;layer.style.backgroundImage=`url('${B+bg}')`;layer.style.clipPath=`circle(${radius}px at 50% 51%)`;layer.style.opacity=String(envelope*.82);ctx.globalCompositeOperation='lighter';for(const s of seeds){const a=s.a+time*.00012*s.speed;const jitter=Math.sin(time*.003+s.a*15)*8;const r=radius+(s.r-.5)*Math.min(75,radius*.23)+jitter;const x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;ctx.globalAlpha=envelope*(.35+s.r*.65);ctx.fillStyle=s.r>.75?'#ffffff':s.r>.35?'#e6ffd1':'#bfecd9';ctx.shadowColor='#efffd8';ctx.shadowBlur=s.size*5;ctx.beginPath();ctx.arc(x,y,s.size*(1+envelope),0,Math.PI*2);ctx.fill();if(s.r>.93){ctx.strokeStyle='#fffde5';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(x-6,y);ctx.lineTo(x+6,y);ctx.moveTo(x,y-6);ctx.lineTo(x,y+6);ctx.stroke();}}ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';}else layer.style.opacity='0';raf=requestAnimationFrame(render);};raf=requestAnimationFrame(render);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);};},[]);
 return <div className="portal-effect" aria-hidden="true"><div ref={reveal} className="portal-reveal"/><canvas ref={canvas}/></div>
}
const data={northstar:[{title:'Cue，把问题变成下一步',desc:'从账号表现出发，把模糊的经营问题拆成具体的内容建议。',prompt:'下条视频拍什么？',result:'围绕开学季，策划「7 天收心计划」：问题开场 → 三个行动 → 互动收尾。',image:'northstar-ui.png',bg:'forest-office.jpg',mode:'cue'},{title:'经营看板，连起内容与增长',desc:'把指标、内容表现与生产排期放在一起，让创作有据可依。',prompt:'看清我的经营重点',result:'经营重点：目标进度、观众特征、内容表现与下一步行动。',image:'northstar-ui.png',bg:'green-gallery.jpg',mode:'dashboard'}],plateforge:[{title:'把今天，规划成一日三餐',desc:'热量目标、饮食偏好和烹饪时间，共同定义适合自己的计划。',prompt:'高蛋白 · 1900 kcal · 30 分钟内',result:'偏好已组合：高蛋白饮食、每日 1900 kcal、30 分钟内完成。',image:'plateforge-ui.png',bg:'food-background.jpg',mode:'meal'},{title:'从已有食材，到下一道菜',desc:'让库存和饮食计划相连接，减少每天重复选择的负担。',prompt:'用冰箱里的食材开始',result:'演示流程：整理食材 → 确认偏好 → 浏览食谱 → 进入烹饪。',image:'plateforge-ui.png',bg:'vegetable-still.jpg',mode:'pantry'}]};
export function FeatureShowcase({product}:{product:'northstar'|'plateforge'}){const [playing,setPlaying]=useState<number|null>(null),[done,setDone]=useState(false);useEffect(()=>{if(playing===null)return;setDone(false);const t=setTimeout(()=>setDone(true),2200);return()=>clearTimeout(t);},[playing]);return <section className={'feature-showcase '+product+'-features'} aria-label={product+'功能展示'}><div className="feature-heading"><span className="eyebrow">IN ACTION / 功能演示</span><h2>{product==='northstar'?'让经营思路，清晰可见。':'少一点纠结，多一点好好吃饭。'}</h2><p>点击演示按钮，看看使用方式。</p></div><div className="feature-grid">{data[product].map((card,i)=><article className={'feature-card '+card.mode} key={card.title}><div className={'feature-stage '+(playing===i?'playing':'')} style={{backgroundImage:`url('${B+card.bg}')`}}><div className="feature-tint"/><div className="feature-device"><div className="device-label">{product==='northstar'?'NorthStar / Workspace':'PlateForge / Daily companion'}<span>✦</span></div><img src={B+card.image} alt={card.title+' · 产品真实界面'} loading="lazy"/><div className="scan-line"/></div><button className="demo-prompt" onClick={()=>{if(playing===i){setPlaying(null);setTimeout(()=>setPlaying(i),30);}else setPlaying(i);}} aria-label={'演示：'+card.title}><span className="demo-star">✦</span><span className="prompt-text">{card.prompt}</span><span className="demo-send">↑</span></button>{playing===i&&<div className="demo-result" aria-live="polite">{done?card.result:'正在演示使用流程…'}</div>}<span className="stage-note">真实 UI · 交互流程演示</span></div><h3>{card.title}</h3><p>{card.desc}</p><button className="demo-link" onClick={()=>{setPlaying(i);setDone(false);if(playing===i)setDone(true);}}>{playing===i?'再次查看演示':'播放功能演示'} ↗</button></article>)}</div><small className="feature-disclaimer">此处为展示动画与预设示例，不调用产品后台。完整功能请通过上方链接打开真实产品。</small></section>}
